/**
 * X-Vault Shared Constants
 * 
 * Single source of truth for all message types used across
 * background.js, dashboard.js, and content.js.
 *
 * Loaded as a plain script (not ES module).
 * Exposes window.MSG for dashboard.js / content.js,
 * and is imported as an ES module by background.js.
 */
const MSG = {
    // Tweet operations
    STORE_TWEET: 'STORE_TWEET',
    DELETE_TWEET: 'DELETE_TWEET',
    GET_TWEETS: 'GET_TWEETS',
    GET_ALL_TWEETS: 'GET_ALL_TWEETS',
    SEARCH: 'SEARCH',
    GET_RECENT_TWEETS: 'GET_RECENT_TWEETS',

    // User operations
    STORE_USER: 'STORE_USER',
    GET_USERS: 'GET_USERS',
    GET_USER: 'GET_USER',
    DELETE_USER: 'DELETE_USER',
    STAR_USER: 'STAR_USER',
    UNSTAR_USER: 'UNSTAR_USER',
    UPDATE_USER_NOTES: 'UPDATE_USER_NOTES',
    ADJUST_TWEET_COUNT: 'ADJUST_TWEET_COUNT',
    ADD_USER_QUICK_TAG: 'ADD_USER_QUICK_TAG',
    REMOVE_USER_QUICK_TAG: 'REMOVE_USER_QUICK_TAG',
    GET_USER_QUICK_TAGS: 'GET_USER_QUICK_TAGS',
    GET_ALL_USER_QUICK_TAGS: 'GET_ALL_USER_QUICK_TAGS',

    // Blocked users
    BLOCK_USER: 'BLOCK_USER',
    UNBLOCK_USER: 'UNBLOCK_USER',
    GET_BLOCKED_USERS: 'GET_BLOCKED_USERS',
    IS_BLOCKED: 'IS_BLOCKED',

    // Settings
    GET_CAPTURE_FROM_HOME: 'GET_CAPTURE_FROM_HOME',
    SET_CAPTURE_FROM_HOME: 'SET_CAPTURE_FROM_HOME',
    GET_HOME_FEED_SETTINGS: 'GET_HOME_FEED_SETTINGS',
    SET_HOME_FEED_SETTINGS: 'SET_HOME_FEED_SETTINGS',
    GET_AI_SETTINGS: 'GET_AI_SETTINGS',
    SET_AI_SETTINGS: 'SET_AI_SETTINGS',

    // Database
    EXPORT_DATABASE: 'EXPORT_DATABASE',
    IMPORT_DATABASE: 'IMPORT_DATABASE',
    DELETE_ALL_DATA: 'DELETE_ALL_DATA',
    GET_TWEET_COUNT: 'GET_TWEET_COUNT',

    // Blog Posts
    STORE_BLOG_POST: 'STORE_BLOG_POST',
    GET_BLOG_POSTS_BY_USER: 'GET_BLOG_POSTS_BY_USER',
    GET_BLOG_POST: 'GET_BLOG_POST',
    UPDATE_BLOG_POST: 'UPDATE_BLOG_POST',
    DELETE_BLOG_POST: 'DELETE_BLOG_POST',

    // Tags / Collections
    TAG_TWEET: 'TAG_TWEET',
    UNTAG_TWEET: 'UNTAG_TWEET',
    GET_TWEET_TAGS: 'GET_TWEET_TAGS',
    GET_TWEETS_BY_TAG: 'GET_TWEETS_BY_TAG',
    GET_ALL_TAGS: 'GET_ALL_TAGS',

    // Auto-Backup
    GET_AUTO_BACKUP_SETTINGS: 'GET_AUTO_BACKUP_SETTINGS',
    SET_AUTO_BACKUP_SETTINGS: 'SET_AUTO_BACKUP_SETTINGS',

    // Bookmarks
    STORE_BOOKMARK: 'STORE_BOOKMARK',
    GET_BOOKMARKS: 'GET_BOOKMARKS',
    GET_BOOKMARK_COUNT: 'GET_BOOKMARK_COUNT',
    DELETE_BOOKMARK: 'DELETE_BOOKMARK',
    CLEAR_BOOKMARKS: 'CLEAR_BOOKMARKS',
    SYNC_BOOKMARKS: 'SYNC_BOOKMARKS',
    BOOKMARK_ADDED: 'BOOKMARK_ADDED',

    // Analytics
    GET_CAPTURE_STATS: 'GET_CAPTURE_STATS',

    // UI
    OPEN_POPUP: 'OPEN_POPUP',
    OPEN_DASHBOARD: 'OPEN_DASHBOARD',
};

// Make available globally for plain scripts
if (typeof window !== 'undefined') {
    window.MSG = MSG;
}
